"""
RAG System - Step 8 of the SimFlo Figma-to-RAG Pipeline.

This package creates RAG (Retrieval-Augmented Generation) knowledge bases from
documentation, code, and tests generated by previous pipeline steps.

Author: SimFlo Pipeline Team
Version: 1.0.0
"""

from .main import (
    RAGSystem,
    RAGProcessingConfig,
    RAGProcessingResult,
    ContentProcessor,
    TextChunker,
    EmbeddingGenerator,
    VectorStore,
    RAGKnowledgeBaseManager
)

__version__ = "1.0.0"
__author__ = "SimFlo Pipeline Team"
__description__ = "RAG System for SimFlo Figma-to-RAG Pipeline"

__all__ = [
    "RAGSystem",
    "RAGProcessingConfig",
    "RAGProcessingResult",
    "ContentProcessor",
    "TextChunker",
    "EmbeddingGenerator",
    "VectorStore",
    "RAGKnowledgeBaseManager"
]
