# -*- coding: utf-8 -*-
"""
RAG System Step - Step 8 of the SimFlo Figma-to-RAG Pipeline.

This module creates RAG (Retrieval-Augmented Generation) knowledge bases from
documentation, code, and tests generated by previous pipeline steps.

Author: SimFlo Pipeline Team
Version: 1.0.0
"""

from common.schemas import (
    ContentChunk, ContentCategory, RAGKnowledgeBase
)
from common.validation import SchemaValidator
import json
import logging
import argparse
import hashlib
import math
import re
import time
import sys
from pathlib import Path
from typing import Dict, List, Any, Optional
from datetime import datetime
from dataclasses import dataclass, field
from collections import defaultdict

# Add parent directory to path for imports
sys.path.append(str(Path(__file__).parent.parent))


try:
    import numpy as np
    HAS_NUMPY = True
except ImportError:
    HAS_NUMPY = False
    logging.warning("NumPy not available. Using mock embeddings.")

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


@dataclass
class RAGProcessingConfig:
    """Configuration for RAG processing."""
    chunk_size: int = 1000  # Target chunk size in tokens
    chunk_overlap: int = 200  # Overlap between chunks
    min_chunk_size: int = 100  # Minimum chunk size
    max_chunk_size: int = 2000  # Maximum chunk size
    embedding_dim: int = 384  # Embedding dimension
    similarity_threshold: float = 0.7  # Similarity threshold for search
    max_search_results: int = 10  # Maximum search results
    include_metadata: bool = True  # Include rich metadata
    strict_validation: bool = False  # Strict validation mode
    generate_mock_embeddings: bool = True  # Generate mock embeddings


@dataclass
class RAGProcessingResult:
    """Result of RAG processing."""
    knowledge_bases: Dict[str, RAGKnowledgeBase]
    statistics: Dict[str, Any]
    processing_time: float
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


class ContentProcessor:
    """Processes different types of content files for RAG ingestion."""

    def __init__(self, config: RAGProcessingConfig):
        self.config = config
        self.supported_extensions = {
            '.md': 'markdown',
            '.txt': 'text',
            '.json': 'json',
            '.js': 'javascript',
            '.jsx': 'javascript',
            '.ts': 'typescript',
            '.tsx': 'typescript',
            '.py': 'python',
            '.css': 'css',
            '.scss': 'scss',
            '.html': 'html',
            '.xml': 'xml',
            '.yaml': 'yaml',
            '.yml': 'yaml'
        }

    def process_file(self, file_path: Path) -> List[Dict[str, Any]]:
        """
        Process a single file and extract content chunks.

        Args:
            file_path: Path to the file to process

        Returns:
            List of content dictionaries with metadata
        """
        try:
            if not file_path.exists():
                logger.warning(f"File not found: {file_path}")
                return []

            # Determine file type
            file_type = self._get_file_type(file_path)
            if not file_type:
                logger.warning(f"Unsupported file type: {file_path.suffix}")
                return []

            # Read file content
            content = self._read_file_content(file_path)
            if not content.strip():
                logger.warning(f"Empty file: {file_path}")
                return []

            # Extract content based on file type
            extracted_content = self._extract_content(content, file_type, file_path)

            logger.debug(f"Processed {file_path}: {len(extracted_content)} sections")
            return extracted_content

        except Exception as e:
            logger.error(f"Error processing file {file_path}: {str(e)}")
            return []

    def _get_file_type(self, file_path: Path) -> Optional[str]:
        """Determine file type from extension."""
        suffix = file_path.suffix.lower()
        return self.supported_extensions.get(suffix)

    def _read_file_content(self, file_path: Path) -> str:
        """Read file content with proper encoding."""
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                return f.read()
        except UnicodeDecodeError:
            # Try different encodings
            for encoding in ['latin-1', 'cp1252']:
                try:
                    with open(file_path, 'r', encoding=encoding) as f:
                        return f.read()
                except UnicodeDecodeError:
                    continue
            raise ValueError(f"Could not read file {file_path} with any supported encoding")

    def _extract_content(self, content: str, file_type: str, file_path: Path) -> List[Dict[str, Any]]:
        """Extract content sections based on file type."""
        if file_type == 'json':
            return self._extract_json_content(content, file_path)
        elif file_type == 'markdown':
            return self._extract_markdown_content(content, file_path)
        elif file_type in ['javascript', 'typescript', 'python', 'css', 'html']:
            return self._extract_code_content(content, file_type, file_path)
        else:
            # Default text processing
            return self._extract_text_content(content, file_path)

    def _extract_json_content(self, content: str, file_path: Path) -> List[Dict[str, Any]]:
        """Extract structured content from JSON files."""
        try:
            data = json.loads(content)
            sections = []

            def extract_recursive(obj, path="root"):
                if isinstance(obj, dict):
                    for key, value in obj.items():
                        current_path = f"{path}.{key}"
                        if isinstance(value, (str, int, float, bool)):
                            sections.append({
                                'content': str(value),
                                'type': 'json_value',
                                'path': current_path,
                                'key': key,
                                'metadata': {
                                    'json_path': current_path,
                                    'data_type': type(value).__name__
                                }
                            })
                        elif isinstance(value, (dict, list)):
                            extract_recursive(value, current_path)
                elif isinstance(obj, list):
                    for i, item in enumerate(obj):
                        current_path = f"{path}[{i}]"
                        if isinstance(item, (str, int, float, bool)):
                            sections.append({
                                'content': str(item),
                                'type': 'json_value',
                                'path': current_path,
                                'key': f"item_{i}",
                                'metadata': {
                                    'json_path': current_path,
                                    'data_type': type(item).__name__
                                }
                            })
                        elif isinstance(item, (dict, list)):
                            extract_recursive(item, current_path)

            extract_recursive(data)
            return sections

        except json.JSONDecodeError as e:
            logger.error(f"Invalid JSON in {file_path}: {str(e)}")
            return []

    def _extract_markdown_content(self, content: str, file_path: Path) -> List[Dict[str, Any]]:
        """Extract structured content from Markdown files."""
        sections = []

        # Split by headers
        lines = content.split('\n')
        current_section = []
        current_header = "Introduction"
        current_level = 0

        for line in lines:
            header_match = re.match(r'^(#{1,6})\s+(.+)$', line)
            if header_match:
                # Save previous section
                if current_section:
                    section_content = '\n'.join(current_section).strip()
                    if section_content:
                        sections.append({
                            'content': section_content,
                            'type': 'markdown_section',
                            'header': current_header,
                            'level': current_level,
                            'metadata': {
                                'header_level': current_level,
                                'header_text': current_header
                            }
                        })

                # Start new section
                current_header = header_match.group(2)
                current_level = len(header_match.group(1))
                current_section = [line]
            else:
                current_section.append(line)

        # Save last section
        if current_section:
            section_content = '\n'.join(current_section).strip()
            if section_content:
                sections.append({
                    'content': section_content,
                    'type': 'markdown_section',
                    'header': current_header,
                    'level': current_level,
                    'metadata': {
                        'header_level': current_level,
                        'header_text': current_header
                    }
                })

        return sections

    def _extract_code_content(self, content: str, file_type: str, file_path: Path) -> List[Dict[str, Any]]:
        """Extract structured content from code files."""
        sections = []

        # Extract functions/classes
        if file_type in ['javascript', 'typescript', 'python']:
            # Function/Class patterns
            patterns = {
                'javascript': [
                    r'function\s+(\w+)\s*\([^)]*\)\s*\{',
                    r'const\s+(\w+)\s*=\s*\([^)]*\)\s*=>\s*\{',
                    r'class\s+(\w+)',
                    r'interface\s+(\w+)'
                ],
                'typescript': [
                    r'function\s+(\w+)\s*\([^)]*\)\s*[:{]',
                    r'const\s+(\w+)\s*=\s*\([^)]*\)\s*=>\s*[:{]',
                    r'class\s+(\w+)',
                    r'interface\s+(\w+)',
                    r'type\s+(\w+)\s*='
                ],
                'python': [
                    r'def\s+(\w+)\s*\([^)]*\)\s*:',
                    r'class\s+(\w+)\s*(\([^)]*\))?\s*:'
                ]
            }

            current_patterns = patterns.get(file_type, [])

            for pattern in current_patterns:
                matches = re.finditer(pattern, content, re.MULTILINE)
                for match in matches:
                    name = match.group(1)
                    start_pos = match.start()

                    # Find the end of the function/class
                    end_pos = self._find_code_block_end(content, start_pos, file_type)

                    if end_pos > start_pos:
                        code_section = content[start_pos:end_pos]
                        sections.append({
                            'content': code_section,
                            'type': 'code_block',
                            'name': name,
                            'language': file_type,
                            'metadata': {
                                'function_name': name,
                                'language': file_type,
                                'start_line': content[:start_pos].count('\n') + 1,
                                'end_line': content[:end_pos].count('\n') + 1
                            }
                        })

        # If no structured sections found, treat whole file as one section
        if not sections:
            sections.append({
                'content': content,
                'type': 'code_file',
                'language': file_type,
                'metadata': {
                    'language': file_type,
                    'file_size': len(content)
                }
            })

        return sections

    def _extract_text_content(self, content: str, file_path: Path) -> List[Dict[str, Any]]:
        """Extract content from plain text files."""
        # Split into paragraphs
        paragraphs = re.split(r'\n\s*\n', content)
        sections = []

        for paragraph in paragraphs:
            paragraph = paragraph.strip()
            if paragraph:
                sections.append({
                    'content': paragraph,
                    'type': 'text_paragraph',
                    'metadata': {
                        'paragraph_length': len(paragraph)
                    }
                })

        return sections

    def _find_code_block_end(self, content: str, start_pos: int, file_type: str) -> int:
        """Find the end of a code block."""
        lines = content[start_pos:].split('\n')
        brace_count = 0
        paren_count = 0
        in_string = False
        escape_next = False

        for i, line in enumerate(lines):
            for j, char in enumerate(line):
                if escape_next:
                    escape_next = False
                    continue

                if char == '\\':
                    escape_next = True
                    continue

                if char in ['"', "'"] and not in_string:
                    in_string = char
                elif char == in_string:
                    in_string = False

                if not in_string:
                    if char == '{':
                        brace_count += 1
                    elif char == '}':
                        brace_count -= 1
                        if brace_count == 0 and i > 0:
                            return start_pos + sum(len(line) + 1 for line in lines[:i]) + j + 1
                    elif char == '(':
                        paren_count += 1
                    elif char == ')':
                        paren_count -= 1

        # If we can't find the end, return the rest of the content
        return len(content)


class TextChunker:
    """Chunks text content for RAG processing with content-aware segmentation."""

    def __init__(self, config: RAGProcessingConfig):
        self.config = config
        self.tokenizer = self._get_tokenizer()

    def _get_tokenizer(self):
        """Get a simple tokenizer for token counting."""
        def simple_tokenizer(text: str) -> List[str]:
            # Simple word-based tokenizer
            words = re.findall(r'\b\w+\b', text.lower())
            return words

        return simple_tokenizer

    def count_tokens(self, text: str) -> int:
        """Count tokens in text."""
        tokens = self.tokenizer(text)
        return len(tokens)

    def chunk_content(self, content_sections: List[Dict[str, Any]], file_path: Path) -> List[ContentChunk]:
        """
        Chunk content sections into RAG-ready chunks.

        Args:
            content_sections: List of content sections from ContentProcessor
            file_path: Original file path

        Returns:
            List of ContentChunk objects
        """
        chunks = []

        for section in content_sections:
            content = section['content']
            section_type = section['type']
            metadata = section.get('metadata', {})

            # Skip very short sections
            if len(content.strip()) < self.config.min_chunk_size:
                continue

            # Determine chunking strategy based on content type
            if section_type in ['json_value', 'code_block']:
                # Don't split structured content
                chunk = self._create_chunk(
                    content=content,
                    chunk_type=section_type,
                    file_path=file_path,
                    section_metadata=metadata,
                    chunk_index=0
                )
                chunks.append(chunk)
            else:
                # Split longer content
                text_chunks = self._split_text(content)
                for i, text_chunk in enumerate(text_chunks):
                    chunk = self._create_chunk(
                        content=text_chunk,
                        chunk_type=section_type,
                        file_path=file_path,
                        section_metadata=metadata,
                        chunk_index=i
                    )
                    chunks.append(chunk)

        return chunks

    def _split_text(self, text: str) -> List[str]:
        """Split text into chunks with overlap."""
        if self.count_tokens(text) <= self.config.chunk_size:
            return [text]

        chunks = []
        sentences = re.split(r'(?<=[.!?])\s+', text)

        current_chunk = ""
        current_tokens = 0

        for sentence in sentences:
            sentence_tokens = self.count_tokens(sentence)

            if current_tokens + sentence_tokens <= self.config.chunk_size:
                current_chunk += sentence + " "
                current_tokens += sentence_tokens
            else:
                # Save current chunk if it's not too small
                if current_tokens >= self.config.min_chunk_size:
                    chunks.append(current_chunk.strip())

                # Start new chunk with overlap
                if len(chunks) > 0:
                    # Add overlap from previous chunk
                    if len(chunks[-1]) > self.config.chunk_overlap:
                        overlap_text = chunks[-1][-self.config.chunk_overlap:]
                    else:
                        overlap_text = chunks[-1]
                    current_chunk = overlap_text + sentence + " "
                    current_tokens = self.count_tokens(current_chunk)
                else:
                    current_chunk = sentence + " "
                    current_tokens = sentence_tokens

        # Add final chunk
        if current_chunk.strip() and current_tokens >= self.config.min_chunk_size:
            chunks.append(current_chunk.strip())

        return chunks

    def _create_chunk(self, content: str, chunk_type: str, file_path: Path,
                      section_metadata: Dict[str, Any], chunk_index: int) -> ContentChunk:
        """Create a ContentChunk object."""
        chunk_id = self._generate_chunk_id(file_path, chunk_index)

        # Determine content type for schema
        content_type_map = {
            'markdown_section': 'documentation',
            'code_block': 'code',
            'code_file': 'code',
            'json_value': 'configuration',
            'text_paragraph': 'documentation'
        }

        content_type = content_type_map.get(chunk_type, 'documentation')

        # Create source information
        source_info = {
            'file_path': str(file_path),
            'file_type': file_path.suffix,
            'chunk_index': chunk_index,
            'section_type': chunk_type
        }

        # Add section-specific metadata
        if chunk_type == 'code_block' and 'function_name' in section_metadata:
            source_info['function_name'] = section_metadata['function_name']

        if chunk_type == 'markdown_section' and 'header_text' in section_metadata:
            source_info['section_title'] = section_metadata['header_text']

        # Generate tags
        tags = self._generate_tags(content, chunk_type, file_path)

        return ContentChunk(
            id=chunk_id,
            content_type=content_type,
            content=content,
            metadata=section_metadata,
            source_info=source_info,
            tags=tags,
            language=self._detect_language(content, file_path)
        )

    def _generate_chunk_id(self, file_path: Path, chunk_index: int) -> str:
        """Generate unique chunk ID."""
        content = f"{file_path}_{chunk_index}_{time.time()}"
        return hashlib.md5(content.encode()).hexdigest()[:12]

    def _generate_tags(self, content: str, chunk_type: str, file_path: Path) -> List[str]:
        """Generate tags for content."""
        tags = [chunk_type]

        # Add file type tags
        suffix = file_path.suffix.lower()
        if suffix in ['.js', '.jsx']:
            tags.extend(['javascript', 'frontend'])
        elif suffix in ['.ts', '.tsx']:
            tags.extend(['typescript', 'frontend'])
        elif suffix == '.py':
            tags.append('python')
        elif suffix == '.json':
            tags.append('json')
        elif suffix == '.md':
            tags.append('markdown')

        # Add content-based tags
        content_lower = content.lower()
        if any(word in content_lower for word in ['react', 'component', 'props']):
            tags.append('react')
        if any(word in content_lower for word in ['test', 'spec', 'expect']):
            tags.append('testing')
        if any(word in content_lower for word in ['design', 'token', 'color', 'font']):
            tags.append('design')
        if any(word in content_lower for word in ['figma', 'design', 'ui']):
            tags.append('figma')

        return tags

    def _detect_language(self, content: str, file_path: Path) -> Optional[str]:
        """Detect content language."""
        suffix = file_path.suffix.lower()

        language_map = {
            '.js': 'javascript',
            '.jsx': 'javascript',
            '.ts': 'typescript',
            '.tsx': 'typescript',
            '.py': 'python',
            '.css': 'css',
            '.scss': 'scss',
            '.html': 'html',
            '.json': 'json',
            '.md': 'markdown'
        }

        return language_map.get(suffix)


class EmbeddingGenerator:
    """Generates embeddings for text chunks."""

    def __init__(self, config: RAGProcessingConfig):
        self.config = config
        self.embedding_dim = config.embedding_dim

    def generate_embeddings(self, chunks: List[ContentChunk]) -> List[ContentChunk]:
        """
        Generate embeddings for content chunks.

        Args:
            chunks: List of ContentChunk objects

        Returns:
            List of ContentChunk objects with embedding vectors
        """
        logger.info(f"Generating embeddings for {len(chunks)} chunks")

        for chunk in chunks:
            if self.config.generate_mock_embeddings:
                chunk.embedding_vector = self._generate_mock_embedding(chunk.content)
            else:
                # In a real implementation, this would use actual embedding models
                chunk.embedding_vector = self._generate_mock_embedding(chunk.content)

        logger.info(f"Generated {len(chunks)} embedding vectors")
        return chunks

    def _generate_mock_embedding(self, text: str) -> List[float]:
        """Generate mock embedding vector based on text content."""
        if HAS_NUMPY:
            # Generate consistent pseudo-random embeddings based on text
            seed = int(hashlib.md5(text.encode()).hexdigest()[:8], 16)
            np.random.seed(seed)
            embedding = np.random.normal(0, 1, self.embedding_dim).tolist()
            # Normalize
            norm = math.sqrt(sum(x * x for x in embedding))
            return [x / norm for x in embedding]
        else:
            # Fallback without numpy
            seed = int(hashlib.md5(text.encode()).hexdigest()[:8], 16)
            import random
            random.seed(seed)
            embedding = [random.gauss(0, 1) for _ in range(self.embedding_dim)]
            # Normalize
            norm = math.sqrt(sum(x * x for x in embedding))
            return [x / norm for x in embedding]


class VectorStore:
    """Mock vector database for storing and searching embeddings."""

    def __init__(self, config: RAGProcessingConfig):
        self.config = config
        self.chunks: List[ContentChunk] = []
        self.index_built = False

    def add_chunks(self, chunks: List[ContentChunk]):
        """Add chunks to the vector store."""
        self.chunks.extend(chunks)
        self.index_built = False
        logger.info(f"Added {len(chunks)} chunks to vector store")

    def build_index(self):
        """Build search index."""
        if not self.chunks:
            logger.warning("No chunks to index")
            return

        # In a real implementation, this would build a proper vector index
        # For now, we'll use a simple approach
        self.index_built = True
        logger.info(f"Built index for {len(self.chunks)} chunks")

    def search(self, query: str, content_type: Optional[str] = None,
               tags: Optional[List[str]] = None, limit: int = None) -> List[ContentChunk]:
        """
        Search for similar chunks.

        Args:
            query: Search query
            content_type: Filter by content type
            tags: Filter by tags
            limit: Maximum number of results

        Returns:
            List of similar ContentChunk objects
        """
        if not self.index_built:
            self.build_index()

        if not self.chunks:
            return []

        limit = limit or self.config.max_search_results

        # Filter chunks
        filtered_chunks = self.chunks

        if content_type:
            filtered_chunks = [c for c in filtered_chunks if c.content_type == content_type]

        if tags:
            filtered_chunks = [c for c in filtered_chunks if any(tag in c.tags for tag in tags)]

        # Simple text search (in real implementation, this would be vector similarity)
        query_lower = query.lower()
        scored_chunks = []

        for chunk in filtered_chunks:
            score = 0

            # Exact match in content
            if query_lower in chunk.content.lower():
                score += 10

            # Word matches
            query_words = query_lower.split()
            content_words = chunk.content.lower().split()
            word_matches = sum(1 for word in query_words if word in content_words)
            score += word_matches * 2

            # Tag matches
            tag_matches = sum(1 for tag in chunk.tags if query_lower in tag.lower())
            score += tag_matches * 3

            # Title/metadata matches
            if 'section_title' in chunk.source_info:
                if query_lower in chunk.source_info['section_title'].lower():
                    score += 5

            if score > 0:
                scored_chunks.append((chunk, score))

        # Sort by score and return top results
        scored_chunks.sort(key=lambda x: x[1], reverse=True)
        return [chunk for chunk, score in scored_chunks[:limit]]

    def get_statistics(self) -> Dict[str, Any]:
        """Get vector store statistics."""
        if not self.chunks:
            return {'total_chunks': 0}

        content_types = defaultdict(int)
        tag_counts = defaultdict(int)

        for chunk in self.chunks:
            content_types[chunk.content_type] += 1
            for tag in chunk.tags:
                tag_counts[tag] += 1

        return {
            'total_chunks': len(self.chunks),
            'content_types': dict(content_types),
            'top_tags': dict(sorted(tag_counts.items(), key=lambda x: x[1], reverse=True)[:10]),
            'index_built': self.index_built
        }


class RAGKnowledgeBaseManager:
    """Manages RAG knowledge bases."""

    def __init__(self, config: RAGProcessingConfig):
        self.config = config
        self.vector_stores: Dict[str, VectorStore] = {}
        self.knowledge_bases: Dict[str, RAGKnowledgeBase] = {}

    def create_knowledge_base(self, name: str, chunks: List[ContentChunk]) -> RAGKnowledgeBase:
        """
        Create a knowledge base from chunks.

        Args:
            name: Knowledge base name
            chunks: List of content chunks

        Returns:
            RAGKnowledgeBase object
        """
        logger.info(f"Creating knowledge base: {name}")

        # Create vector store
        vector_store = VectorStore(self.config)
        vector_store.add_chunks(chunks)
        vector_store.build_index()

        # Create content categories
        categories = self._create_categories(chunks)

        # Create knowledge base
        knowledge_base = RAGKnowledgeBase(
            project_name=name,
            version="1.0.0",
            chunks=chunks,
            categories=categories,
            metadata={
                'created_at': datetime.now().isoformat(),
                'total_chunks': len(chunks),
                'config': self.config.__dict__
            },
            configuration={
                'chunk_size': self.config.chunk_size,
                'embedding_dim': self.config.embedding_dim,
                'similarity_threshold': self.config.similarity_threshold
            }
        )

        self.knowledge_bases[name] = knowledge_base
        self.vector_stores[name] = vector_store

        logger.info(f"Created knowledge base {name} with {len(chunks)} chunks")
        return knowledge_base

    def _create_categories(self, chunks: List[ContentChunk]) -> List[ContentCategory]:
        """Create content categories from chunks."""
        categories = []

        # Group by content type
        type_groups = defaultdict(list)
        for chunk in chunks:
            type_groups[chunk.content_type].append(chunk)

        for content_type, type_chunks in type_groups.items():
            category = ContentCategory(
                name=content_type,
                description=f"Content of type {content_type}",
                metadata={
                    'chunk_count': len(type_chunks),
                    'total_size': sum(len(chunk.content) for chunk in type_chunks)
                }
            )
            categories.append(category)

        return categories

    def save_knowledge_base(self, name: str, output_dir: Path):
        """Save knowledge base to files."""
        if name not in self.knowledge_bases:
            raise ValueError(f"Knowledge base '{name}' not found")

        kb = self.knowledge_bases[name]
        kb_dir = output_dir / f"{name}-rag"
        kb_dir.mkdir(parents=True, exist_ok=True)

        # Save knowledge base
        kb_file = kb_dir / "knowledge-base.json"
        with open(kb_file, 'w', encoding='utf-8') as f:
            json.dump(kb.dict(), f, indent=2, default=str)

        # Save chunks separately for easier access
        chunks_dir = kb_dir / "chunks"
        chunks_dir.mkdir(exist_ok=True)

        for chunk in kb.chunks:
            chunk_file = chunks_dir / f"{chunk.id}.json"
            with open(chunk_file, 'w', encoding='utf-8') as f:
                json.dump(chunk.dict(), f, indent=2, default=str)

        # Save configuration
        config_file = kb_dir / "rag-config.json"
        with open(config_file, 'w', encoding='utf-8') as f:
            json.dump(kb.configuration, f, indent=2)

        # Save statistics
        stats_file = kb_dir / "statistics.json"
        vector_store = self.vector_stores[name]
        stats = vector_store.get_statistics()
        stats['knowledge_base'] = name
        stats['saved_at'] = datetime.now().isoformat()

        with open(stats_file, 'w', encoding='utf-8') as f:
            json.dump(stats, f, indent=2)

        logger.info(f"Saved knowledge base '{name}' to {kb_dir}")

    def get_knowledge_base(self, name: str) -> Optional[RAGKnowledgeBase]:
        """Get knowledge base by name."""
        return self.knowledge_bases.get(name)

    def search_knowledge_base(self, name: str, query: str, **kwargs) -> List[ContentChunk]:
        """Search within a knowledge base."""
        if name not in self.vector_stores:
            raise ValueError(f"Knowledge base '{name}' not found")

        return self.vector_stores[name].search(query, **kwargs)

    def list_knowledge_bases(self) -> List[str]:
        """List all knowledge base names."""
        return list(self.knowledge_bases.keys())


class RAGSystem:
    """Main RAG system orchestrator."""

    def __init__(self, config: RAGProcessingConfig):
        self.config = config
        self.content_processor = ContentProcessor(config)
        self.text_chunker = TextChunker(config)
        self.embedding_generator = EmbeddingGenerator(config)
        self.kb_manager = RAGKnowledgeBaseManager(config)
        self.validator = SchemaValidator()

    def process_pipeline_outputs(self, input_dirs: List[Path], output_dir: Path) -> RAGProcessingResult:
        """
        Process outputs from previous pipeline steps into RAG knowledge bases.

        Args:
            input_dirs: List of directories containing pipeline outputs
            output_dir: Output directory for RAG knowledge bases

        Returns:
            RAGProcessingResult with statistics and metadata
        """
        start_time = time.time()
        errors = []
        warnings = []

        logger.info(f"Starting RAG processing from {len(input_dirs)} input directories")

        try:
            # Collect all files
            all_files = self._collect_files(input_dirs)
            logger.info(f"Found {len(all_files)} files to process")

            # Process files by type
            processed_chunks = []
            processing_stats = defaultdict(lambda: {'files': 0, 'chunks': 0})

            for file_path in all_files:
                try:
                    # Process file content
                    content_sections = self.content_processor.process_file(file_path)
                    if not content_sections:
                        continue

                    # Chunk content
                    chunks = self.text_chunker.chunk_content(content_sections, file_path)
                    if not chunks:
                        continue

                    processed_chunks.extend(chunks)

                    # Update statistics
                    file_type = file_path.suffix.lower()
                    processing_stats[file_type]['files'] += 1
                    processing_stats[file_type]['chunks'] += len(chunks)

                    logger.debug(f"Processed {file_path}: {len(chunks)} chunks")

                except Exception as e:
                    error_msg = f"Error processing file {file_path}: {str(e)}"
                    logger.error(error_msg)
                    errors.append(error_msg)

            # Generate embeddings
            processed_chunks = self.embedding_generator.generate_embeddings(processed_chunks)

            # Create knowledge bases by content type
            knowledge_bases = {}

            # Documentation knowledge base
            doc_chunks = [c for c in processed_chunks if c.content_type == 'documentation']
            if doc_chunks:
                kb = self.kb_manager.create_knowledge_base('doc-rag', doc_chunks)
                knowledge_bases['doc-rag'] = kb
                self.kb_manager.save_knowledge_base('doc-rag', output_dir)

            # Code knowledge base
            code_chunks = [c for c in processed_chunks if c.content_type == 'code']
            if code_chunks:
                kb = self.kb_manager.create_knowledge_base('code-rag', code_chunks)
                knowledge_bases['code-rag'] = kb
                self.kb_manager.save_knowledge_base('code-rag', output_dir)

            # Test knowledge base
            test_chunks = [c for c in processed_chunks if c.content_type == 'test' or 'test' in c.tags]
            if test_chunks:
                kb = self.kb_manager.create_knowledge_base('test-rag', test_chunks)
                knowledge_bases['test-rag'] = kb
                self.kb_manager.save_knowledge_base('test-rag', output_dir)

            # Configuration knowledge base
            config_chunks = [c for c in processed_chunks if c.content_type == 'configuration']
            if config_chunks:
                kb = self.kb_manager.create_knowledge_base('config-rag', config_chunks)
                knowledge_bases['config-rag'] = kb
                self.kb_manager.save_knowledge_base('config-rag', output_dir)

            # Compile statistics
            processing_time = time.time() - start_time
            statistics = {
                'processing_time': processing_time,
                'total_files_processed': sum(stats['files'] for stats in processing_stats.values()),
                'total_chunks_created': len(processed_chunks),
                'knowledge_bases_created': len(knowledge_bases),
                'file_type_stats': dict(processing_stats),
                'chunk_types': defaultdict(int)
            }

            for chunk in processed_chunks:
                statistics['chunk_types'][chunk.content_type] += 1

            statistics['chunk_types'] = dict(statistics['chunk_types'])

            # Create main RAG configuration file
            self._save_rag_configuration(output_dir, knowledge_bases, statistics)

            logger.info(f"RAG processing completed in {processing_time:.2f}s")
            logger.info(f"Created {len(knowledge_bases)} knowledge bases with {len(processed_chunks)} total chunks")

            return RAGProcessingResult(
                knowledge_bases=knowledge_bases,
                statistics=statistics,
                processing_time=processing_time,
                errors=errors,
                warnings=warnings,
                metadata={
                    'input_directories': [str(d) for d in input_dirs],
                    'output_directory': str(output_dir),
                    'config': self.config.__dict__
                }
            )

        except Exception as e:
            error_msg = f"RAG processing failed: {str(e)}"
            logger.error(error_msg)
            errors.append(error_msg)

            return RAGProcessingResult(
                knowledge_bases={},
                statistics={},
                processing_time=time.time() - start_time,
                errors=errors,
                warnings=warnings
            )

    def _collect_files(self, input_dirs: List[Path]) -> List[Path]:
        """Collect all files from input directories."""
        all_files = []

        for input_dir in input_dirs:
            if not input_dir.exists():
                logger.warning(f"Input directory does not exist: {input_dir}")
                continue

            # Recursively find all files
            for file_path in input_dir.rglob('*'):
                if file_path.is_file() and file_path.suffix.lower() in self.content_processor.supported_extensions:
                    all_files.append(file_path)

        return sorted(all_files)

    def _save_rag_configuration(self, output_dir: Path, knowledge_bases: Dict[str, RAGKnowledgeBase],
                                statistics: Dict[str, Any]):
        """Save main RAG configuration file."""
        config = {
            'rag_system': {
                'version': '1.0.0',
                'created_at': datetime.now().isoformat(),
                'knowledge_bases': list(knowledge_bases.keys()),
                'total_chunks': sum(len(kb.chunks) for kb in knowledge_bases.values()),
                'configuration': self.config.__dict__
            },
            'statistics': statistics,
            'knowledge_bases': {
                name: {
                    'chunk_count': len(kb.chunks),
                    'categories': len(kb.categories),
                    'version': kb.version
                }
                for name, kb in knowledge_bases.items()
            }
        }

        config_file = output_dir / 'rag-config.json'
        with open(config_file, 'w', encoding='utf-8') as f:
            json.dump(config, f, indent=2, default=str)

        logger.info(f"Saved RAG configuration to {config_file}")


def main():
    """Main entry point for the RAG system."""
    parser = argparse.ArgumentParser(
        description='RAG System - Step 8 of the SimFlo Figma-to-RAG Pipeline',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Process pipeline outputs
  python v2/rag-system/main.py --input ./output --output ./rag-output

  # Process multiple input directories
  python v2/rag-system/main.py --input ./output ./examples --output ./rag-output

  # Custom chunking configuration
  python v2/rag-system/main.py --input ./output --output ./rag-output --chunk-size 500 --overlap 100

  # Strict validation mode
  python v2/rag-system/main.py --input ./output --output ./rag-output --strict
        """
    )

    parser.add_argument(
        '--input', '-i',
        nargs='+',
        required=True,
        help='Input directories containing pipeline outputs'
    )

    parser.add_argument(
        '--output', '-o',
        type=Path,
        required=True,
        help='Output directory for RAG knowledge bases'
    )

    parser.add_argument(
        '--chunk-size',
        type=int,
        default=1000,
        help='Target chunk size in tokens (default: 1000)'
    )

    parser.add_argument(
        '--overlap',
        type=int,
        default=200,
        help='Chunk overlap in tokens (default: 200)'
    )

    parser.add_argument(
        '--min-chunk-size',
        type=int,
        default=100,
        help='Minimum chunk size in tokens (default: 100)'
    )

    parser.add_argument(
        '--embedding-dim',
        type=int,
        default=384,
        help='Embedding dimension (default: 384)'
    )

    parser.add_argument(
        '--max-results',
        type=int,
        default=10,
        help='Maximum search results (default: 10)'
    )

    parser.add_argument(
        '--strict',
        action='store_true',
        help='Enable strict validation mode'
    )

    parser.add_argument(
        '--verbose', '-v',
        action='store_true',
        help='Enable verbose logging'
    )

    args = parser.parse_args()

    # Configure logging
    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    # Create configuration
    config = RAGProcessingConfig(
        chunk_size=args.chunk_size,
        chunk_overlap=args.overlap,
        min_chunk_size=args.min_chunk_size,
        embedding_dim=args.embedding_dim,
        max_search_results=args.max_results,
        strict_validation=args.strict
    )

    # Validate inputs
    input_dirs = [Path(input_dir) for input_dir in args.input]
    output_dir = Path(args.output)

    # Create output directory
    output_dir.mkdir(parents=True, exist_ok=True)

    try:
        # Create RAG system
        rag_system = RAGSystem(config)

        # Process pipeline outputs
        result = rag_system.process_pipeline_outputs(input_dirs, output_dir)

        # Handle errors
        if result.errors and config.strict_validation:
            logger.error("Processing completed with errors in strict mode:")
            for error in result.errors:
                logger.error(f"  - {error}")
            sys.exit(1)
        elif result.errors:
            logger.warning("Processing completed with errors:")
            for error in result.errors:
                logger.warning(f"  - {error}")

        # Print summary
        print("\n✅ RAG System Processing Complete")
        print(f"   Processing time: {result.processing_time:.2f}s")
        print(f"   Files processed: {result.statistics.get('total_files_processed', 0)}")
        print(f"   Chunks created: {result.statistics.get('total_chunks_created', 0)}")
        print(f"   Knowledge bases: {len(result.knowledge_bases)}")
        print(f"   Output directory: {output_dir}")

        if result.statistics.get('file_type_stats'):
            print("\n📊 File Type Statistics:")
            for file_type, stats in result.statistics['file_type_stats'].items():
                print(f"   {file_type}: {stats['files']} files, {stats['chunks']} chunks")

        if result.knowledge_bases:
            print("\n📚 Knowledge Bases Created:")
            for name, kb in result.knowledge_bases.items():
                print(f"   {name}: {len(kb.chunks)} chunks")

        if result.warnings:
            print("\n⚠️  Warnings:")
            for warning in result.warnings:
                print(f"   - {warning}")

        # Test search functionality
        if result.knowledge_bases and not args.verbose:
            print("\n🔍 Testing Search Functionality:")
            test_queries = ["React component", "design token", "test scenario"]

            for query in test_queries:
                results = rag_system.kb_manager.search_knowledge_base('doc-rag', query, limit=3)
                print(f"   Query '{query}': {len(results)} results")

    except Exception as e:
        logger.error(f"RAG system failed: {str(e)}")
        if args.verbose:
            import traceback
            traceback.print_exc()
        sys.exit(1)


if __name__ == '__main__':
    main()
