import React, { useState } from 'react';
import './App.css';
import { Button, Card, Input, Badge } from './components';
import { Code, Play, Eye, Layers } from 'lucide-react';

function App() {
  const [activeTab, setActiveTab] = useState('components');

  const tabs = [
    { id: 'components', label: 'Generated Components', icon: Layers },
    { id: 'preview', label: 'Live Preview', icon: Eye },
    { id: 'code', label: 'Code Samples', icon: Code },
    { id: 'pipeline', label: 'Pipeline Info', icon: Play },
  ];

  return (
    <div className="App">
      <header className="App-header">
        <div className="container">
          <h1>🎨 SimFlo Figma-to-RAG Pipeline Demo</h1>
          <p>Transform your Figma designs into production-ready React applications</p>
        </div>
      </header>

      <main className="container">
        <div className="tabs">
          {tabs.map((tab) => {
            const Icon = tab.icon;
            return (
              <button
                key={tab.id}
                className={`tab-button ${activeTab === tab.id ? 'active' : ''}`}
                onClick={() => setActiveTab(tab.id)}
              >
                <Icon size={16} />
                {tab.label}
              </button>
            );
          })}
        </div>

        <div className="tab-content">
          {activeTab === 'components' && <ComponentsShowcase />}
          {activeTab === 'preview' && <LivePreview />}
          {activeTab === 'code' && <CodeSamples />}
          {activeTab === 'pipeline' && <PipelineInfo />}
        </div>
      </main>

      <footer>
        <div className="container">
          <p>Generated by SimFlo Figma-to-RAG Pipeline • 9-Step Automated Process</p>
        </div>
      </footer>
    </div>
  );
}

function ComponentsShowcase() {
  return (
    <div className="showcase">
      <h2>🎨 Generated Components</h2>
      <p>These components were automatically generated from Figma designs</p>

      <div className="component-grid">
        <div className="component-card">
          <h3>Button Component</h3>
          <div className="component-preview">
            <Button variant="primary">Primary Button</Button>
            <Button variant="secondary">Secondary Button</Button>
            <Button variant="outline">Outline Button</Button>
            <Button variant="ghost">Ghost Button</Button>
          </div>
        </div>

        <div className="component-card">
          <h3>Card Component</h3>
          <div className="component-preview">
            <Card>
              <h4>Sample Card</h4>
              <p>This is a sample card component generated from Figma designs.</p>
              <Button variant="primary">Action</Button>
            </Card>
          </div>
        </div>

        <div className="component-card">
          <h3>Input Component</h3>
          <div className="component-preview">
            <Input placeholder="Enter your email" type="email" />
            <Input placeholder="Enter password" type="password" />
            <Input placeholder="Search..." type="search" />
          </div>
        </div>

        <div className="component-card">
          <h3>Badge Component</h3>
          <div className="component-preview">
            <Badge variant="success">Success</Badge>
            <Badge variant="warning">Warning</Badge>
            <Badge variant="error">Error</Badge>
            <Badge variant="info">Info</Badge>
          </div>
        </div>
      </div>
    </div>
  );
}

function LivePreview() {
  return (
    <div className="showcase">
      <h2>👀 Live Preview</h2>
      <p>Interactive preview of the generated application</p>

      <Card>
        <h3>Sample Application Screen</h3>
        <p>This demonstrates how the generated components work together in a real application context.</p>

        <div style={{ display: 'grid', gap: '1rem', marginTop: '1rem' }}>
          <Input placeholder="User name" />
          <Input placeholder="Email address" type="email" />
          <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
            <Badge variant="info">User Type: Premium</Badge>
            <Badge variant="success">Active</Badge>
          </div>
          <div style={{ display: 'flex', gap: '0.5rem' }}>
            <Button variant="primary">Save Changes</Button>
            <Button variant="outline">Cancel</Button>
          </div>
        </div>
      </Card>
    </div>
  );
}

function CodeSamples() {
  const buttonCode = `// Generated Button Component
interface ButtonProps {
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost';
  size?: 'sm' | 'md' | 'lg';
  children: React.ReactNode;
  onClick?: () => void;
}

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'md',
  children,
  onClick
}) => {
  const baseClasses = 'btn';
  const variantClasses = \`btn-\${variant}\`;
  const sizeClasses = \`btn-\${size}\`;

  return (
    <button
      className={\`\${baseClasses} \${variantClasses} \${sizeClasses}\`}
      onClick={onClick}
    >
      {children}
    </button>
  );
};`;

  return (
    <div className="showcase">
      <h2>💻 Code Samples</h2>
      <p>TypeScript code generated by the pipeline</p>

      <div className="code-sample">
        <h3>Generated Button Component</h3>
        <pre>
          <code>{buttonCode}</code>
        </pre>
      </div>
    </div>
  );
}

function PipelineInfo() {
  return (
    <div className="showcase">
      <h2>🚀 Pipeline Information</h2>
      <p>The SimFlo Figma-to-RAG Pipeline consists of 9 automated steps:</p>

      <div className="pipeline-steps">
        <div className="step">
          <span className="step-number">1</span>
          <div className="step-content">
            <h4>figma-analyzer</h4>
            <p>Extract design tokens and components from Figma</p>
          </div>
        </div>

        <div className="step">
          <span className="step-number">2</span>
          <div className="step-content">
            <h4>prototype-analyzer</h4>
            <p>Analyze user interactions and flows</p>
          </div>
        </div>

        <div className="step">
          <span className="step-number">3</span>
          <div className="step-content">
            <h4>token-converter</h4>
            <p>Convert design tokens to framework formats</p>
          </div>
        </div>

        <div className="step">
          <span className="step-number">4</span>
          <div className="step-content">
            <h4>component-generator</h4>
            <p>Generate React components</p>
          </div>
        </div>

        <div className="step">
          <span className="step-number">5</span>
          <div className="step-content">
            <h4>page-generator</h4>
            <p>Create page implementations</p>
          </div>
        </div>

        <div className="step">
          <span className="step-number">6</span>
          <div className="step-content">
            <h4>test-generator</h4>
            <p>Generate Playwright test suites</p>
          </div>
        </div>

        <div className="step">
          <span className="step-number">7</span>
          <div className="step-content">
            <h4>test-runner</h4>
            <p>Execute tests and provide demo</p>
          </div>
 </div>

        <div className="step">
          <span className="step-number">8</span>
          <div className="step-content">
            <h4>rag-system</h4>
            <p>Create RAG knowledge bases</p>
          </div>
        </div>

        <div className="step">
          <span className="step-number">9</span>
          <div className="step-content">
            <h4>ai-assistant</h4>
            <p>AI-powered code analysis and review</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;